version: "3.9"
services:
  backend:
    build:
      context: ./back-end
    ports:
      - "8800:8800"
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front-end
    ports:
      - "80:80"
    restart: always
